### ISSUE TITLE
Copy icon disappeared from toolbar after update to DW 2018-04-22 "Greebo"

### ISSUE THREAD

**Issue by fthommen** [orangain/dokuwiki-copypage-plugin#12]
After having updated DW to 2018-04-22 "Greebo" (using the Update plugin), the "Copy" icon disappeared from the toolbar.  Reinstalling the plugin didn't help

**Comment by orangain** [comment]
@fthommen Thank you for the reporting issue!

I've fixed and released a new version of the plugin to support DokuWiki 2018-04-22 "Greebo". Please upgrade the plugin from plugin manager.

If you have any problem, please feel free to reopen this issue.
