### ISSUE TITLE
The button doesn't appear

### ISSUE THREAD

**Issue by hokkaidoperson** [orangain/dokuwiki-copypage-plugin#13]
Nice to meet you.  I recently started to use your plugin.

I applied the copypage plugin, but "copy the page" button doesn't appear.
From smart phones, the choice to copy pages appears in the pulldown, but the text "copy the page" isn't shown.

I'm using the GreenSteel template, and using the wiki in Japanese surrounding.

Can you investigate this issue and modify the plugin?
I'll show you more information about the issue if you want.

Thanks.

**Comment by orangain** [comment]
@hokkaidoperson Thank you for using the plugin. I've investigated the issue.

Unfortunately, [GreenSteel template](https://www.dokuwiki.org/template:greensteel) seems to be too old and it does not support DokuWiki's API to add menu items used by the copypage plugin. 

As you say, a menu item appears in dropdown menu for mobile devices when using the GreenSteel template, but it's just lucky. It does not means the template supports the plugin.

Please use another template, or ask the template author to support DokuWiki's [Menu API](https://www.dokuwiki.org/devel:menus).

NOTE: Default template of DokuWiki 2018-04-22 “Greebo” is only supported by the latest version of the plugin just released today. If you don't see the copy page button, please upgrade the plugin to the latest version.

**Comment by hokkaidoperson** [comment]
Thanks for your investigation.

I consider to use another template.
