### ISSUE TITLE
Action unknow: copypageplugin_copy

### ISSUE THREAD

**Issue by blu28** [orangain/dokuwiki-copypage-plugin#15]
Pressing copy page button returns an error:
"Action unknown: copypageplugin_copy"

**Comment by orangain** [comment]
@blu28 The plugin works well in my environment.

* DokuWiki version: 2018-04-22c
* DokuWiki template: DokuWiki Template (default)
* Browser: Google Chrome

Please let me know your environment. 

* What version of DokuWiki do you use?
* What kind of DokuWiki template do you use if you change it from the default one?
* What kind of browser do you use?

**Comment by blu28** [comment]
I don't know what changed, but it is working now.
