### ISSUE TITLE
Compatibility with "Hogfather"

### ISSUE THREAD

**Issue by r4taw2mg** [orangain/dokuwiki-copypage-plugin#16]
Hi, 

is there any chance, this plugin will get compatibility with the latest version of DokuWiki?

**Comment by orangain** [comment]
@r4taw2mg Sorry for not replying earlier. I've just confirmed that the copypage plugin works as expected in the latest version, 2020-07-29 "Hogfather", of DokuWiki. Do you have some trouble in that version? Or do you mean that compatibility marker in [the plugin page](https://www.dokuwiki.org/plugin:copypage) should be green?

**Comment by r4taw2mg** [comment]
Hi, @orangain Thanks for the reply, which was absolutely timely for me.

The plugin didn't work right after installations and the plugin was shown as unclear on the plugin page. Maybe I did make a mistake, but checking again this very moment, copypage seems to be fully compatibel with Release 2020-07-29 "Hogfather".

**Comment by orangain** [comment]
@r4taw2mg I'm glad to hear that! I've marked that the plugin is compatible with Hogfather on [the plugin page](https://www.dokuwiki.org/plugin:copypage).
