### ISSUE TITLE
Tools bar moving

### ISSUE THREAD

**Issue by Grahack** [orangain/dokuwiki-copypage-plugin#2]
Hi,
Thanks for your plugin.
I noticed that when I hover over the tool bar, the bar kind of expands.
It's like there was some margin/padding but I found nothing in the files.
Am I alone to notice this ? I could provide two screenshots if needed.

**Comment by Grahack** [comment]
A quick fix:

    #dokuwiki__pagetools:hover ul li a,
    #dokuwiki__pagetools ul li a:focus,
    #dokuwiki__pagetools ul li a:active {
        width: auto;
        height: auto;
        overflow: visible;
        padding: 1px 40px 5px 5px;       // CHANGED THIS FROM 5px TO 1px
        background-image: url(images/pagetools-sprite.png?v=2);
    }

**Comment by orangain** [comment]
I'm sorry for not replying sooner. Could you provide screenshots and tell me what kind of OS and browser you use?

**Comment by orangain** [comment]
I'm closing this issue because it has been inactive for a long time. Please feel free to reopen this issue if you need any further help.
