### ISSUE TITLE
Cancel does not cancel but starts editing top-level start page

### ISSUE THREAD

**Issue by vincentkersten** [orangain/dokuwiki-copypage-plugin#6]
Hi Orangain, 
when i hit cancel in the copypage dialog box, it jumps to 
https://example.com/doku.php?id=&do=edit&copyfrom=the_page_I_was
effectively landing in the toplevel 'start' page in edit mode (prolly because the id=  is blank) instead of just closing the dialog. 

Thanks again,

  Vincent

**Comment by orangain** [comment]
Hi Vincent,

Hmm... That's weird. Hitting cancel button should just close the dialog. What kind of browser and OS do you use?

**Comment by vincentkersten** [comment]
Hi orangain,
seeing this in Safari (9.0.3) on OSX.

Now checking in Firefox; after hitting cancel it does not jump to edit, so there everything is normal ... 

Getting back to Safari opening the error console , nothing weird pops up, somehow this gets triggered in Safari, might be a glich in Safari?

If you want me to test something just shout!

**Comment by orangain** [comment]
Hi Vincent,

It was due to the well-known incompatibility between Safari and other browsers, though I didn't know that. I've fixed and released the new version. Please try upgrading or re-installing the plugin.
